name: flutter_smartlook
description: Smartlook SDK wrapper for Flutter. Analyze user behavior in ways never possible before.
version: 4.1.3
homepage: https://www.smartlook.com/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.Smartlook.Smartlook.flutter_smartlook
        pluginClass: SmartlookPlugin
      ios:
        pluginClass: SmartlookPlugin

  assets:
   - lib/smartlook.png
